/**
 * Assertions over the recital↔article map (curated editorial layer).
 * Runs after verify-amendments.ts in `npm run verify`.
 *
 * Two regimes, keyed on source meta.complete:
 * - while false (curation in progress): structural checks only — key
 *   completeness, slug validity, inverse consistency between byRecital and
 *   byArticle, independent recheck of the generated file against the source;
 * - once true: additionally pin reviewedCount === 180, the exact pair count,
 *   and editorial spot checks (filled in when curation finishes).
 */
import assert from "node:assert";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type {
  AmendmentsGenerated,
  Article,
  Recital,
  RecitalMapGenerated,
  RecitalMapSource,
} from "../src/lib/types";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const load = <T>(rel: string): T => JSON.parse(readFileSync(join(root, rel), "utf-8"));

const source = load<RecitalMapSource>("data/source/recital-article-map.json");
const generated = load<RecitalMapGenerated>("data/generated/recital-map.json");
const articles = load<Article[]>("data/generated/articles.json");
const recitals = load<Recital[]>("data/generated/recitals.json");
const amendments = load<AmendmentsGenerated>("data/generated/amendments.json");

// Pinned at curation completion (meta.complete flips true): exact totals and
// a few hand-checked mappings.
const EXPECTED: { pairCount: number | null; spot: Record<string, string[]> | null } = {
  pairCount: null,
  spot: null,
};

// ------------------------------------------------- structural checks

const validSlugs = new Set<string>([
  ...articles.map((a) => String(a.number)),
  ...amendments.newArticles.map((n) => n.slug),
]);
const recitalKeys = recitals.map((r) => String(r.number));

assert.equal(recitalKeys.length, 180, "base corpus has 180 recitals");
assert.deepEqual(
  Object.keys(source.recitals).sort((a, b) => Number(a) - Number(b)),
  recitalKeys,
  "source keys are exactly recitals 1–180",
);

// independent recheck: rebuild both directions from the source and compare
let pairCount = 0;
let reviewedCount = 0;
const wantByRecital: Record<string, Set<string>> = {};
const wantByArticle: Record<string, Set<number>> = {};
for (const [k, entry] of Object.entries(source.recitals)) {
  assert.equal(typeof entry.reviewed, "boolean", `recital ${k}: reviewed is boolean`);
  if (entry.reviewed) reviewedCount++;
  assert.equal(
    new Set(entry.articles).size,
    entry.articles.length,
    `recital ${k}: no duplicate articles`,
  );
  for (const slug of entry.articles) {
    assert.ok(validSlugs.has(slug), `recital ${k}: article slug "${slug}" exists`);
    (wantByRecital[k] ??= new Set()).add(slug);
    (wantByArticle[slug] ??= new Set()).add(Number(k));
    pairCount++;
  }
}

assert.deepEqual(
  Object.fromEntries(Object.entries(generated.byRecital).map(([k, v]) => [k, new Set(v)])),
  wantByRecital,
  "generated byRecital matches source",
);
assert.deepEqual(
  Object.fromEntries(Object.entries(generated.byArticle).map(([k, v]) => [k, new Set(v)])),
  wantByArticle,
  "generated byArticle matches source",
);
assert.equal(generated.meta.pairCount, pairCount, "meta.pairCount");
assert.equal(generated.meta.reviewedCount, reviewedCount, "meta.reviewedCount");
assert.equal(generated.meta.complete, source.meta.complete, "meta.complete mirrors source");

// inverse consistency of the generated file itself
for (const [k, slugs] of Object.entries(generated.byRecital)) {
  assert.ok(slugs.length > 0, `byRecital ${k}: empty entries are omitted`);
  for (const slug of slugs)
    assert.ok(generated.byArticle[slug]?.includes(Number(k)), `byRecital ${k}→${slug} inverted`);
}
for (const [slug, nums] of Object.entries(generated.byArticle)) {
  assert.ok(nums.length > 0, `byArticle ${slug}: empty entries are omitted`);
  assert.deepEqual(nums, [...nums].sort((a, b) => a - b), `byArticle ${slug}: ascending`);
  for (const n of nums)
    assert.ok(generated.byRecital[String(n)]?.includes(slug), `byArticle ${slug}→${n} inverted`);
}

// ------------------------------------------------- completeness pin

if (source.meta.complete) {
  assert.ok(
    EXPECTED.pairCount !== null && EXPECTED.spot !== null,
    "meta.complete is true — pin EXPECTED counts in verify-recital-map.ts",
  );
  assert.equal(reviewedCount, 180, "every recital human-reviewed");
  assert.equal(pairCount, EXPECTED.pairCount, "exact pair count");
  for (const [k, slugs] of Object.entries(EXPECTED.spot!))
    assert.deepEqual(generated.byRecital[k] ?? [], slugs, `spot check: recital ${k}`);
}

console.log(
  `verify-recital-map: all assertions passed ` +
    `(${pairCount} pairs, reviewed ${reviewedCount}/180, complete=${source.meta.complete})`,
);
